### ISSUE TITLE
Zones custom inputs

### ISSUE THREAD

**Issue by vinod-melarkode** [crowbarz/aiopioneer#10]
Thank you very much for this integration.

I have a Pioneer VSX-923K receiver and some of the autodetected inputs are not working (they are not present on the receiver).
I tried to customize the sources but those for zone_2 and zone_h are not changing.
In the dashboard I see all the sources from the main zone.

My config is:
```
- platform: pioneer_async
  name: Pioneer AVR
  host: avr.cr.home.lan
  port: 23
  scan_interval: 60
  timeout: 5.0
  sources:
    "Wii U": "25"
    "HD1": "04"
    "PS4": "06"
    "VE1": "15"
    "PS3": "22"
    "HDMI5/MHL": "23"
    "Switch": "24"
    "XBOX360": "34"
    "Internet Radio": "38"
    "Media Server": "44"
    "Favourites": "45"
    "Ipod/USB": "17"
    "TV": "05"
    "CD": "01"
    "Tuner": "02"
    "Adapter Port": "33"
  params:
    ignore_volume_check: true
    zone_2_sources: ["04", "06", "15", "05", "01", "02", "33"]
    zone_h_sources: ["25", "04", "06", "15", "22", "23", "24", "34"]
```

**Comment by crowbarz** [comment]
There may be another step required to update the HA integration to use the per-zone sources list, that functionality was added to the API module relatively recently. Will be looking into this.

Note that `zone_h_sources` is currently inconsistent with HDZone references elsewhere, which uses zone Z. This is to be fixed, but as part of that the `params` item will be renamed at which time you'll need to update the configuration.

**Comment by 11harveyj** [comment]
The integration needs to be updated to pass the zone information into the function in the API to return the current source, a lot of the recent functionality added to this API hasn't been added to the integration yet.

**Comment by vinod-melarkode** [comment]
Thank you for the feedback.
I'll wait for the updates.

**Comment by crowbarz** [comment]
This has been implemented in https://github.com/crowbarz/ha-pioneer_async/ release 0.7.3. You can also specify zone subsets via the UI configuration now.

Note that param `zone_h_sources` has been renamed to `zone_z_sources`, but I will be renaming that again to `hdz_sources` in a future release for better consistency. (That will be flagged as a breaking change.)
