### ISSUE TITLE
Older Pioneer HDZones not detected

### ISSUE THREAD

**Issue by 11harveyj** [crowbarz/aiopioneer#3]
Hello!

Got a older SC-LX57 amp and using with your HA Pioneer addon just fine... Noticed however the HDZone is not picked up..

After doing some tests, it looks like we try to query the volume for the HDZone which fails on this amp. I've managed to find a random Excel document full of supported commands, it looks like volume is not supported for HDZone's on this amp.. When running command "?HZV" in telnet, the amp returns E04.

Removing the volume check will pickup the HDZone correctly but this might not work so great for other devices.

Commands found here, although would highly recommend using Excel or something on a local machine as the document never loaded in a web browser.

https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.pioneerelectronics.com%2FStaticFiles%2FCustom%2520Install%2FRS-232%2520Codes%2FAv%2520Receivers%2FElite%2520%26%2520Pioneer%2520FY13AVR%2520IP%2520%26%2520RS-232%25205-8-12.xls&wdOrigin=BROWSELINK

**Comment by crowbarz** [comment]
Thanks for logging, yes you are right in that a zone is not currently added if the volume check fails. Some recent discussion already on a different AVR with slightly different capabilities for HDZone:

https://community.home-assistant.io/t/pioneer-avr-integration-supporting-config-flow-and-asyncio/221547/22

Do you know if you can set and/or step volume though API commands on the SC-LX57 despite it not reporting volume via the API? eg. can this be done via a remote control app, which also connects to the AVR via the API.

I have been thinking about a number of possible solutions to this class of issue:

- removing the volume check for all devices
- adding a parameter to selectively disable the volume check
- adding the ability to specify zones that are always enabled, skipping the checks

**Comment by 11harveyj** [comment]
No way to change the volume of the HDZone unfortunately, as bromarc339 said on the forum, its just passed through AV straight to the HDZone HDMI out port. 
Neither the app nor the remote has the ability to change the hdzone volume as far as I can tell. It's simply just an on and an off (even on the unit itself)

I think your second option, may be a good starting point? Perhaps a list of models that don't support volume on HDZone, if current model matches one of those, don't check it. I know the models on the functions page of that Excel doc doesn't support it (as it's not even listed under the zones control) although amps like SC-LX57 isn't actually listed so I wouldn't say it's a "definite" list but something that could work as a starting point. 

Happy to help where I can of course! Just my python knowledge is a tad rusty lol.

**Comment by crowbarz** [comment]
What model is your AVR detected as? In HA you can find that in `Configuration > Devices` and searching for your AVR. I will ignore the volume check if param `ignore_volume_check` is set to `True` (defaults to `False`) and default this to `True` for models known to contain zones that don't support querying volume level.

I took a look at the Excel document you linked to and it doesn't mention HDZone anywhere, so not sure how to come up with a list of applicable models. The parameter will be settable from options to allow it to be enabled manually.

**Comment by 11harveyj** [comment]
HDZone is zone 4 in that documentation I think (it is on there, I just don't have computer on to double check)

HA reports the following:

`SC-LX57
by Pioneer
Firmware: 1-149-020-516-118`

**Comment by crowbarz** [comment]
This should be fixed in [aiopioneer](https://github.com/crowbarz/aiopioneer) 0.1.8 and [ha-pioneer_async](https://github.com/crowbarz/ha-pioneer_async) 0.6.1.

A custom profile was added for SC-LX57 to set `ignore_volume_check` to `true`, you should see a debug log message from `aiopioneer` like the one below if the profile is applied.

```
applying default parameters for model SC-LX57
```

If the integration is added via the HA UI, you might need to check the the `ignore_volume_check` manually and then restart HA, or alternatively remove/re-add the integration to pick up the new defaults for this AVR model.

**Comment by 11harveyj** [comment]
All seems to be working. Just needed to update the integration and restart, no re-config required and its picked up the HDZone too :)

**Comment by crowbarz** [comment]
Cool, thanks for confirming.
